### PR TITLE
Fixes #13 - adds INSTALL.md

### LINKED ISSUE #13: Move installation section to INSTALL.md
Installation can be quite a long section, but only needs to be read once (ideally). Having it in the main readme hurts scan-ability and detracts from reading over usage and config instructions.

[The instructions](https://github.com/cfpb/open-source-project-template#installation) say an external file can be linked to, but perhaps this repo should set a precedence of having installation instructions in their own file like the contributing doc and changelog are? 

I'd suggest:

- Move all installation instructions to `INSTALL.md` in the project root directory.
- Simply have the readme list this for installation instructions:
```markdown
## Installation
Follow the instructions in [INSTALL](INSTALL.md).
```

### PR DESCRIPTION
**Pull request by anselmbradford**
Adds INSTALL.md file and updates instructions.

## Additions

- Fixes #13 - adds INSTALL.md.

## Removals

- Removes extraneous whitespace in README.md.

## Changes

- Links to INSTALL.md from README.md.

## Review

- @Scotchester
- @ascott1
- @contolini
- @marcesher et al

### CODE REVIEW

**Comment by Scotchester** [comment]
The only concern I have with this is if people decide to put the instructions in the README and don't delete the `INSTALL.md` file, there's an empty file hanging around. But I guess we already have similar issues with the screenshot and the checklist, so what's one more?

**Comment by contolini** [comment]
@Scotchester Yeah, I wouldn't worry about it. There's a certain degree of repo hygiene that people should be expected to maintain and deleting unnecessary files is a part of that.

**Comment by anselmbradford** [comment]
Added h1 in https://github.com/anselmbradford/open-source-project-template/commit/a7d8069f497f187dcb0e5bb2c3b2cd9cea7da71e

Also removed extraneous whitespace from CONTRIBUTING.md while I was at it.

**Comment by anselmbradford** [comment]
Is this good to squash?

**Comment by contolini** [comment]
:+1: Looks good here.

**Comment by anselmbradford** [comment]
sq-wah-sshhhhd

**Pull request merged**
