### PR TITLE
Update TERMS.md

### PR DESCRIPTION
**Pull request by anselmbradford**
Removes block of blank space from end of TERMS.md.

## Removals

- Removes trailing block of newlines.

### CODE REVIEW

**Comment by Scotchester** [comment]
Couldn'ta done this in #15? :stuck_out_tongue_winking_eye: 

Let's make sure there are no other whitespace fixes to handle in this repo, while you're at it, if you haven't already.

**Comment by anselmbradford** [comment]
Sorry, just saw it and used the GH UI to edit.... allll riiight I'll checkout the branch ;-P

**Comment by anselmbradford** [comment]
Found some additional newlines in https://github.com/anselmbradford/open-source-project-template/commit/8c5774f3b74023e960c819cc79d95a64f9ace5b4, but otherwise I didn't see anything else.

**Comment by Scotchester** [comment]
:+1:

**Pull request merged**
